AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: UCR Library LibApps Cloud applicaton

Resources:
  ProjectsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: key
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ProjectUpdatesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: key
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  RecurringTasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  RecurringTaskInstancesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  RequestsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Projects:
    Type: AWS::Serverless::Function
    Properties:
      Handler: projects.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          PROJECTS_TABLE_NAME: !Ref ProjectsTable
      Events:
        ListProjects:
          Type: Api
          Properties:
            Path: /projects
            Method: get
        CreateProject:
          Type: Api
          Properties:
            Path: /projects
            Method: post
        Project:
          Type: Api
          Properties:
            Path: /project/{project}
            Method: any